;/*FB_PKG_DELIM*/

__d("CometInputWithCommands.react",["CometComponentWithKeyCommands.react","CometKeys","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e.useMemo;function c(e){var t=o("react-compiler-runtime").c(36),n=e.children,a=e.delete,i=e.down,l=e.enter,u=e.esc,c=e.isInline,d=e.tab,m=e.up,p=e.xstyle,_;if(t[0]!==a||t[1]!==i||t[2]!==l||t[3]!==u||t[4]!==d||t[5]!==m){if(_=[],l!=null){var f;t[7]===Symbol.for("react.memo_cache_sentinel")?(f={key:r("CometKeys").ENTER},t[7]=f):f=t[7];var g;t[8]!==l.description||t[9]!==l.handler?(g={command:f,description:l.description,handler:l.handler,triggerFromInputs:!0},t[8]=l.description,t[9]=l.handler,t[10]=g):g=t[10],_.push(g)}if(a!=null){var h;t[11]===Symbol.for("react.memo_cache_sentinel")?(h={key:r("CometKeys").DELETE},t[11]=h):h=t[11];var y;t[12]!==a.description||t[13]!==a.handler?(y={command:h,description:a.description,handler:a.handler,triggerFromInputs:!0},t[12]=a.description,t[13]=a.handler,t[14]=y):y=t[14],_.push(y)}if(m!=null){var C;t[15]===Symbol.for("react.memo_cache_sentinel")?(C={key:r("CometKeys").UP},t[15]=C):C=t[15];var b;t[16]!==m.description||t[17]!==m.handler?(b={command:C,description:m.description,handler:m.handler,triggerFromInputs:!0},t[16]=m.description,t[17]=m.handler,t[18]=b):b=t[18],_.push(b)}if(i!=null){var v;t[19]===Symbol.for("react.memo_cache_sentinel")?(v={key:r("CometKeys").DOWN},t[19]=v):v=t[19];var S;t[20]!==i.description||t[21]!==i.handler?(S={command:v,description:i.description,handler:i.handler,triggerFromInputs:!0},t[20]=i.description,t[21]=i.handler,t[22]=S):S=t[22],_.push(S)}if(d!=null){var R;t[23]===Symbol.for("react.memo_cache_sentinel")?(R={key:r("CometKeys").TAB},t[23]=R):R=t[23];var L;t[24]!==d.description||t[25]!==d.handler?(L={command:R,description:d.description,handler:d.handler,triggerFromInputs:!0},t[24]=d.description,t[25]=d.handler,t[26]=L):L=t[26],_.push(L)}if(u!=null){var E;t[27]===Symbol.for("react.memo_cache_sentinel")?(E={key:r("CometKeys").ESCAPE},t[27]=E):E=t[27];var k;t[28]!==u.description||t[29]!==u.handler?(k={command:E,description:u.description,handler:u.handler,triggerFromInputs:!0},t[28]=u.description,t[29]=u.handler,t[30]=k):k=t[30],_.push(k)}t[0]=a,t[1]=i,t[2]=l,t[3]=u,t[4]=d,t[5]=m,t[6]=_}else _=t[6];var I=_,T=c===!0?"span":"div",D;return t[31]!==n||t[32]!==I||t[33]!==T||t[34]!==p?(D=s.jsx(r("CometComponentWithKeyCommands.react"),{commandConfigs:I,debugName:"InputSubmit",elementType:T,xstyle:p,children:n}),t[31]=n,t[32]=I,t[33]=T,t[34]=p,t[35]=D):D=t[35],D}l.default=c}),98);
__d("FBNucleusCheckmarkCircleOutline20Icon.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsxs("svg",babelHelpers.extends({viewBox:"0 0 20 20",width:"1em",height:"1em",fill:"currentColor"},e,{children:[e.title!=null&&s.jsx("title",{children:e.title}),e.children!=null&&s.jsx("defs",{children:e.children}),s.jsx("path",{d:"M14.78 8.28a.75.75 0 0 0-1.06-1.06l-4.794 4.793a.25.25 0 0 1-.353 0L6.28 9.72a.75.75 0 1 0-1.06 1.061l2.292 2.292a1.75 1.75 0 0 0 2.475 0L14.78 8.28z"}),s.jsx("path",{d:"M10 .5a9.5 9.5 0 1 0 0 19 9.5 9.5 0 0 0 0-19zM2 10a8 8 0 1 1 16 0 8 8 0 0 1-16 0z"})]}))}u.displayName=u.name+" [from "+i.id+"]",u._size=20,u._isSVG=!0;var c=u;l.default=c}),98);
__d("LWIOmniButton.react",["cr:12080","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e=["ref"],s,u=s||(s=o("react"));function c(t){var r=o("react-compiler-runtime").c(6),a,i;r[0]!==t?(i=t.ref,a=babelHelpers.objectWithoutPropertiesLoose(t,e),r[0]=t,r[1]=a,r[2]=i):(a=r[1],i=r[2]);var l;return r[3]!==a||r[4]!==i?(l=u.jsx(n("cr:12080"),babelHelpers.extends({},a,{ref:i})),r[3]=a,r[4]=i,r[5]=l):l=r[5],l}l.default=c}),98);
__d("LWITetraButtonBase.react",["FDSButton.react","FDSIcon.react","react"],(function(t,n,r,o,a,i,l){"use strict";var e=["ref"],s=["addOnSecondary","isLoading","minWidth","shouldNotFill","variantOverride"],u,c=u||(u=o("react"));function d(t){var n=t.ref,o=babelHelpers.objectWithoutPropertiesLoose(t,e),a=o.addOnSecondary,i=o.isLoading,l=o.minWidth,u=o.shouldNotFill,d=o.variantOverride,m=babelHelpers.objectWithoutPropertiesLoose(o,s),p=c.jsx(r("FDSButton.react"),babelHelpers.extends({},m,{endContent:a!=null?c.jsx(r("FDSIcon.react"),{color:a.color,icon:a.icon}):void 0,ref:n}));return l==null?p:c.jsx("div",{style:{minWidth:l},children:p})}d.displayName=d.name+" [from "+i.id+"]",l.default=d}),98);
__d("ManagedError",[],(function(t,n,r,o,a,i){var e=(function(e){function t(t,n){var r;return r=e.call(this,t!=null?t:"")||this,t!=null?r.message=t:r.message="",r.innerError=n,r}return babelHelpers.inheritsLoose(t,e),t})(babelHelpers.wrapNativeSuper(Error));i.default=e}),66);
__d("RelayFBEnvironmentFactory",["RelayFBEnvironmentDefinitions"],(function(t,n,r,o,a,i,l){"use strict";var e=o("RelayFBEnvironmentDefinitions").createEnvironmentFactory(function(e){return{configName:"RelayFBEnvironment",actorID:e}});l.default=e}),98);
__d("generateRandomKey",[],(function(t,n,r,o,a,i){"use strict";var e={},l=Math.pow(2,24);function s(){for(var t;t===void 0||Object.prototype.hasOwnProperty.call(e,t)||!isNaN(+t);)t=Math.floor(Math.random()*l).toString(32);return e[t]=!0,t}a.exports=s}),null);
__d("createRawDraftContentState",["generateRandomKey"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t,n){var o=[];return{blocks:[{depth:0,entityRanges:t!=null?t:[],inlineStyleRanges:o,key:r("generateRandomKey")(),text:e,type:"unstyled"}],entityMap:n!=null?n:{}}}l.default=e}),98);
__d("createCometComposerRawDraftContentStateFromTextWithEntities",["createRawDraftContentState"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t){var n=e.text;if(e.ranges.length===0)return r("createRawDraftContentState")(e.text);var o=[],a={},i=0;return e.ranges.forEach(function(e){var n=e.length,r=e.offset,l=t==null?void 0:t(e);l!=null&&(a[i.toString()]=l,o.push({key:i,length:n,offset:r}),i+=1)}),r("createRawDraftContentState")(n,o,a)}l.default=e}),98);
__d("createCometComposerAgnosticEditorState",["createCometComposerRawDraftContentStateFromTextWithEntities"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t,n){var o={ranges:t,text:e},a=r("createCometComposerRawDraftContentStateFromTextWithEntities")(o,n);return{initialRawContentState:a}}l.default=e}),98);
__d("createCometComposerRawDraftMentionsEntity",[],(function(t,n,r,o,a,i){"use strict";function e(e){return{data:{id:e},mutability:"SEGMENTED",type:"MENTION"}}i.default=e}),66);
__d("isSoftNewlineEvent",["Keys"],(function(t,n,r,o,a,i){"use strict";function e(e){return e.which===n("Keys").RETURN&&(e.getModifierState("Shift")||e.getModifierState("Alt")||e.getModifierState("Control"))}a.exports=e}),null);
__d("useRefEffect",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useCallback,c=s.useRef;function d(e,t){var n=c(null);return u(function(t){n.current&&(n.current(),n.current=null),t!=null&&(n.current=e(t))},t)}l.default=d}),98);