;/*FB_PKG_DELIM*/

__d("CometUFIConstants",[],(function(t,n,r,o,a,i){"use strict";var e=525,l=750,s={INLINE_COMPOSER:"INLINE_COMPOSER",UFI:"UFI"};i.REACTION_MENU_SHOW_DELAY=e,i.REACTION_MENU_HIDE_DELAY=l,i.RTA_ENTRYPOINT_TAG=s}),66);
__d("FBProfile_enable_perf_improv_gk.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("gkx")("18615")}};l.default=e}),98);
__d("FBUnifiedVideoAdsAdInfoButton_menuItem.graphql",[],(function(t,n,r,o,a,i){"use strict";var e={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"FBUnifiedVideoAdsAdInfoButton_menuItem",selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},{alias:null,args:null,concreteType:"SponsoredData",kind:"LinkedField",name:"sponsored_data",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"ad_id",storageKey:null}],storageKey:null},{alias:null,args:null,concreteType:"XFBTransparencyAdInfo",kind:"LinkedField",name:"transparency_ad_info",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"menu_label",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"should_display_ad_info",storageKey:null}],storageKey:null}],type:"Story",abstractKey:null};a.exports=e}),null);
__d("FBUnifiedVideoAdsAdInfoButton.react",["AdInfoLoggingHooks","CometEntryPointDialogTrigger.react","CometPoliticalInfosheetDialogV2.entrypoint","CometRelay","FBNucleusDocumentOutline20Icon.react","FBUnifiedVideoAdsAdInfoButton_menuItem.graphql","FDSMenuItem.react","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s,u=s||(s=o("react"));function c(t){var a,i,l,s=o("react-compiler-runtime").c(13),c=t.menuItemData,d=o("CometRelay").useFragment(e!==void 0?e:e=n("FBUnifiedVideoAdsAdInfoButton_menuItem.graphql"),c),m=d==null?void 0:d.id,p=d==null||(a=d.sponsored_data)==null?void 0:a.ad_id,_=d==null||(i=d.transparency_ad_info)==null?void 0:i.menu_label,f=d==null||(l=d.transparency_ad_info)==null?void 0:l.should_display_ad_info,g=o("AdInfoLoggingHooks").useLogAdInfoImpression(p!=null?p:"","reels"),h=o("AdInfoLoggingHooks").useLogAdInfoClick(p!=null?p:"","reels");if(m==null||p==null||_==null||f!==!0)return null;var y;s[0]!==p?(y={adID:p},s[0]=p,s[1]=y):y=s[1];var C;s[2]!==p||s[3]!==m?(C={ad_id:p,story_id:m},s[2]=p,s[3]=m,s[4]=C):C=s[4];var b;s[5]!==g||s[6]!==h||s[7]!==_?(b=function(t){return u.jsx(r("FDSMenuItem.react"),{icon:r("FBNucleusDocumentOutline20Icon.react"),onClick:function(){h(),t()},primaryText:_,ref:g})},s[5]=g,s[6]=h,s[7]=_,s[8]=b):b=s[8];var v;return s[9]!==y||s[10]!==C||s[11]!==b?(v=u.jsx(r("CometEntryPointDialogTrigger.react"),{dialogEntryPoint:r("CometPoliticalInfosheetDialogV2.entrypoint"),otherProps:y,preloadParams:C,children:b}),s[9]=y,s[10]=C,s[11]=b,s[12]=v):v=s[12],v}l.default=c}),98);
__d("FBUnifiedVideoFeedbackBar_comet_reels_save_button_gk.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("gkx")("2350")}};l.default=e}),98);
__d("FBUnifiedVideoMediaFooter_comet_enable_reels_ads_gk.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("gkx")("7085")}};l.default=e}),98);
__d("FBUnifiedVideoMediaFooter_enable_group_character_ai_info_pill_gk.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("gkx")("15595")}};l.default=e}),98);
__d("FBUnifiedVideoMediaFooter_enable_meta_ai_pill_gk.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("gkx")("18341")}};l.default=e}),98);
__d("FBUnifiedVideoMediaFooter_enable_video_augment_pills_gk.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("gkx")("7749")}};l.default=e}),98);
__d("FBUnifiedVideoMenu_fb_reels_ranking_debug_tool_gk.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("gkx")("21334")}};l.default=e}),98);
__d("ProfileCometAboutAppSectionQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26227086583653611"}),null);
__d("ShouldEnableBakedInTextUnifiedVideo.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("gkx")("20985")}};l.default=e}),98);
__d("ProfileCometAboutAppSectionQuery$Parameters",["CometUFIReactionsEnableShortName.relayprovider","FBProfile_enable_perf_improv_gk.relayprovider","FBReelsMediaFooter_comet_enable_reels_ads_gk.relayprovider","FBReels_deprecate_short_form_video_context_gk.relayprovider","FBReels_enable_view_dubbed_audio_type_gk.relayprovider","FBUnifiedVideoFeedbackBar_comet_reels_save_button_gk.relayprovider","FBUnifiedVideoMediaFooter_comet_enable_reels_ads_gk.relayprovider","FBUnifiedVideoMediaFooter_enable_group_character_ai_info_pill_gk.relayprovider","FBUnifiedVideoMediaFooter_enable_meta_ai_pill_gk.relayprovider","FBUnifiedVideoMediaFooter_enable_video_augment_pills_gk.relayprovider","FBUnifiedVideoMenu_fb_reels_ranking_debug_tool_gk.relayprovider","ProfileCometAboutAppSectionQuery_facebookRelayOperation","ShouldEnableBakedInTextUnifiedVideo.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("ProfileCometAboutAppSectionQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometAboutAppSectionQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__FBProfile_enable_perf_improv_gkrelayprovider:n("FBProfile_enable_perf_improv_gk.relayprovider"),__relay_internal__pv__CometUFIReactionsEnableShortNamerelayprovider:n("CometUFIReactionsEnableShortName.relayprovider"),__relay_internal__pv__FBReels_deprecate_short_form_video_context_gkrelayprovider:n("FBReels_deprecate_short_form_video_context_gk.relayprovider"),__relay_internal__pv__FBReelsMediaFooter_comet_enable_reels_ads_gkrelayprovider:n("FBReelsMediaFooter_comet_enable_reels_ads_gk.relayprovider"),__relay_internal__pv__ShouldEnableBakedInTextUnifiedVideorelayprovider:n("ShouldEnableBakedInTextUnifiedVideo.relayprovider"),__relay_internal__pv__FBUnifiedVideoMediaFooter_comet_enable_reels_ads_gkrelayprovider:n("FBUnifiedVideoMediaFooter_comet_enable_reels_ads_gk.relayprovider"),__relay_internal__pv__FBUnifiedVideoMediaFooter_enable_meta_ai_pill_gkrelayprovider:n("FBUnifiedVideoMediaFooter_enable_meta_ai_pill_gk.relayprovider"),__relay_internal__pv__FBUnifiedVideoMediaFooter_enable_group_character_ai_info_pill_gkrelayprovider:n("FBUnifiedVideoMediaFooter_enable_group_character_ai_info_pill_gk.relayprovider"),__relay_internal__pv__FBUnifiedVideoMediaFooter_enable_video_augment_pills_gkrelayprovider:n("FBUnifiedVideoMediaFooter_enable_video_augment_pills_gk.relayprovider"),__relay_internal__pv__FBUnifiedVideoFeedbackBar_comet_reels_save_button_gkrelayprovider:n("FBUnifiedVideoFeedbackBar_comet_reels_save_button_gk.relayprovider"),__relay_internal__pv__FBReels_enable_view_dubbed_audio_type_gkrelayprovider:n("FBReels_enable_view_dubbed_audio_type_gk.relayprovider"),__relay_internal__pv__FBUnifiedVideoMenu_fb_reels_ranking_debug_tool_gkrelayprovider:n("FBUnifiedVideoMenu_fb_reels_ranking_debug_tool_gk.relayprovider")}}};a.exports=e}),null);
__d("ProfileCometAboutTabRouteRoot.entrypoint",["JSResourceForInteraction","ProfileCometAboutAppSectionQuery$Parameters","WebPixelRatio","buildCometProfileRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCometProfileRoute.entrypoint")(r("JSResourceForInteraction")("ProfileCometAboutTabRoot.react").__setRef("ProfileCometAboutTabRouteRoot.entrypoint"),function(e){var t=e.routeProps,n=t.collectionToken,a=t.rawSectionToken,i=t.sectionToken,l=t.userID;return{queries:{aboutAppSectionQueryReference:{parameters:r("ProfileCometAboutAppSectionQuery$Parameters"),variables:{appSectionFeedKey:"ProfileCometAppSectionFeed_timeline_nav_app_sections__"+(a!=null?a:i),collectionToken:n,pageID:String(l),rawSectionToken:a,scale:o("WebPixelRatio").get(),sectionToken:i,showReactions:!0,userID:String(l)}}}}});l.default=e}),98);